[project]
name = "Senior_Design_Team_22_meshtastic_software"
requires-python = ">=3.12, <3.15"
dynamic = ["version"]
dependencies = [
"numpy",
"pyside6",
]
[tool.pyside6-project]
[tool.setuptools]
py-modules = ["main", "teams", "ui_PCUI"]
